
name: Node.js CI

on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Instal npm deps
      run: |
        npm ci
    - name: Run linter
      run: |
        npx eslint .
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TEST_ID }}
      with:
        coverageCommand: npm test -- --coverage --coverageProvider=v8
        debug: true
